//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<Партнер> Партнер { get; set; }
        public virtual DbSet<Поставка_продукта> Поставка_продукта { get; set; }
        public virtual DbSet<Продукт> Продукт { get; set; }
        public virtual DbSet<Состав_продукта> Состав_продукта { get; set; }
        public virtual DbSet<Тип_материала> Тип_материала { get; set; }
        public virtual DbSet<Тип_партнера> Тип_партнера { get; set; }
        public virtual DbSet<Тип_продукта> Тип_продукта { get; set; }
    }
}
