//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставка_продукта
    {
        public int Код { get; set; }
        public Nullable<int> Продукция { get; set; }
        public Nullable<int> Код_партнера { get; set; }
        public Nullable<int> Количество_продукции { get; set; }
    
        public virtual Партнер Партнер { get; set; }
        public virtual Продукт Продукт { get; set; }
    }
}
