//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукт()
        {
            this.Поставка_продукта = new HashSet<Поставка_продукта>();
            this.Состав_продукта = new HashSet<Состав_продукта>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_продукции { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставка_продукта> Поставка_продукта { get; set; }
        public virtual Тип_продукта Тип_продукта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_продукта> Состав_продукта { get; set; }
    }
}
