//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnologies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_продукта
    {
        public int Код { get; set; }
        public Nullable<int> Материал { get; set; }
        public Nullable<int> Продукт { get; set; }
    
        public virtual Материал Материал1 { get; set; }
        public virtual Продукт Продукт1 { get; set; }
    }
}
